# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Run UnitTests"
  lane :unit_test do
    run_tests(
      scheme: "CircleCIDemoTests",
      devices: ["iPhone 13 (15.4)"]
    )
  end

  desc "Run all UITests"
  lane :ui_test_all do
    run_tests(
      scheme: "CircleCIDemoUITests",
      devices: ["iPhone 13 (15.4)"]
    )
  end

  desc "Run all UITests"
  lane :build_for_uitest do
    run_tests(
      scheme: "CircleCIDemoUITests",
      devices: ["iPhone 13 (15.4)"]
      derived_data_path: "dist",
      build_for_testing: true
    )
  end

  desc "Run specific UITests"
  lane :ui_test do
    run_tests(
      scheme: "CircleCIDemoUITests",
      devices: ["iPhone 13 (15.4)"],
      only_testing: "CircleCIDemoUITests/CircleCIDemoUITests5"
    )
  end

  lane :beta do
    match(type: "adhoc")
    build_app(
      scheme: "CircleCIDemo",
      configuration: "Debug",
      export_method: "ad-hoc"
    )
    firebase_app_distribution(
      app: "1:137851785924:ios:2c201eae2f71ed0af2ef91"
    )
  end
end
