# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Run UnitTests"
  lane :unit_test do
    run_tests(
      scheme: "CircleCIDemoTests",
      devices: ["iPhone 13 (15.0)"],
      derived_data_path: "./dist"
    )
  end

  lane :beta do
    build_app(
      scheme: "CircleCIDemo",
      derived_data_path: "./dist"
    )
  end
end
